### ISSUE TITLE
Cannot reproduce the PointGroup Detector performance

### ISSUE THREAD

**Issue by CurryYuan** [daveredrum/D3Net#3]
Hi @daveredrum ,

I follow the instruction in README to train the PointGroup Detector, but the mAP@50 is around 32, which is quite low. 
```
python scripts/train.py --config conf/pointgroup.yaml
```
I test the given checkpoint, and I can get the result of 50 mAP@50. So I guess there is something wrong with the given training hyper-parameters. Can you check it?

Thanks for your help.

Best

**Comment by daveredrum** [comment]
Hi @CurryYuan, could you quickly check if you can get reasonable results using the [checkpoint](https://www.dropbox.com/s/nsrbcfeihmh2bhw/D3Net.7z?dl=0)?

**Comment by CurryYuan** [comment]
Yes, the checkpoint can get satisfactory results. As I said above, I can get the detection result mAP@50 around 50 with the given checkpoint.

**Comment by Chuan-shanjia** [comment]
Hi, @CurryYuan ,
Did you meet the error  https://github.com/daveredrum/D3Net/issues/5#issue-1594636475 ?
I met a similiar error using the [checkpoint](https://www.dropbox.com/s/nsrbcfeihmh2bhw/D3Net.7z?dl=0):
Traceback (most recent call last):
  File "scripts/eval.py", line 522, in <module>
    model = init_model(cfg, dataset)
  File "scripts/eval.py", line 121, in init_model
    model.load_state_dict(checkpoint["state_dict"], strict=False)
  File "/home/niexing/anaconda3/envs/mmdet3d_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PipelineNet:
        size mismatch for embeddings: copying a param with shape torch.Size([3441, 300]) from checkpoint, the shape in current model is torch.Size([3433, 300]).

If you have met this error, how can you fix it?
Thank you!
